name: ScriptBlox Scanner

on:
  schedule:
    - cron: '* * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests

    - name: Run ScriptBlox Scanner
      env:
        GH_GIST_TOKEN: ${{ secrets.GH_GIST_TOKEN }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: python main.py
